// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PoyRunner {
	
	
	public partial class Upload {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile FastaFile;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile SpatialFile;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox TextBoxNumberOfNodes;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxTotalTimeHours;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator2;
		
		protected System.Web.UI.WebControls.TextBox TextBoxTotalTimeMinutes;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator4;
		
		protected System.Web.UI.WebControls.TextBox TextBoxSearchTimeHours;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator3;
		
		protected System.Web.UI.WebControls.TextBox TextBoxSearchTimeHoursMinutes;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator5;
		
		protected System.Web.UI.WebControls.Button Submit;
	}
}
