//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace PoyTestClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Init", ReplyAction="*")]
        System.IAsyncResult BeginInit(System.AsyncCallback callback, object asyncState);
        
        int EndInit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AddFile", ReplyAction="*")]
        System.IAsyncResult BeginAddFile(PoyTestClient.ServiceReference1.AddFileRequest request, System.AsyncCallback callback, object asyncState);
        
        PoyTestClient.ServiceReference1.AddFileResponse EndAddFile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Submit", ReplyAction="*")]
        System.IAsyncResult BeginSubmit(PoyTestClient.ServiceReference1.SubmitRequest request, System.AsyncCallback callback, object asyncState);
        
        PoyTestClient.ServiceReference1.SubmitResponse EndSubmit(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IsDoneYet", ReplyAction="*")]
        System.IAsyncResult BeginIsDoneYet(int jobId, System.AsyncCallback callback, object asyncState);
        
        bool EndIsDoneYet(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFile", Namespace="http://tempuri.org/", Order=0)]
        public PoyTestClient.ServiceReference1.AddFileRequestBody Body;
        
        public AddFileRequest() {
        }
        
        public AddFileRequest(PoyTestClient.ServiceReference1.AddFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int jobId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] fileData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        public AddFileRequestBody() {
        }
        
        public AddFileRequestBody(int jobId, byte[] fileData, string fileName) {
            this.jobId = jobId;
            this.fileData = fileData;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public PoyTestClient.ServiceReference1.AddFileResponseBody Body;
        
        public AddFileResponse() {
        }
        
        public AddFileResponse(PoyTestClient.ServiceReference1.AddFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddFileResult;
        
        public AddFileResponseBody() {
        }
        
        public AddFileResponseBody(bool AddFileResult) {
            this.AddFileResult = AddFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Submit", Namespace="http://tempuri.org/", Order=0)]
        public PoyTestClient.ServiceReference1.SubmitRequestBody Body;
        
        public SubmitRequest() {
        }
        
        public SubmitRequest(PoyTestClient.ServiceReference1.SubmitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int jobId;
        
        public SubmitRequestBody() {
        }
        
        public SubmitRequestBody(int jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitResponse", Namespace="http://tempuri.org/", Order=0)]
        public PoyTestClient.ServiceReference1.SubmitResponseBody Body;
        
        public SubmitResponse() {
        }
        
        public SubmitResponse(PoyTestClient.ServiceReference1.SubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] SubmitResult;
        
        public SubmitResponseBody() {
        }
        
        public SubmitResponseBody(byte[] SubmitResult) {
            this.SubmitResult = SubmitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : PoyTestClient.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsDoneYetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IsDoneYetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<PoyTestClient.ServiceReference1.Service1Soap>, PoyTestClient.ServiceReference1.Service1Soap {
        
        private BeginOperationDelegate onBeginInitDelegate;
        
        private EndOperationDelegate onEndInitDelegate;
        
        private System.Threading.SendOrPostCallback onInitCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddFileDelegate;
        
        private EndOperationDelegate onEndAddFileDelegate;
        
        private System.Threading.SendOrPostCallback onAddFileCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubmitDelegate;
        
        private EndOperationDelegate onEndSubmitDelegate;
        
        private System.Threading.SendOrPostCallback onSubmitCompletedDelegate;
        
        private BeginOperationDelegate onBeginIsDoneYetDelegate;
        
        private EndOperationDelegate onEndIsDoneYetDelegate;
        
        private System.Threading.SendOrPostCallback onIsDoneYetCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<InitCompletedEventArgs> InitCompleted;
        
        public event System.EventHandler<AddFileCompletedEventArgs> AddFileCompleted;
        
        public event System.EventHandler<SubmitCompletedEventArgs> SubmitCompleted;
        
        public event System.EventHandler<IsDoneYetCompletedEventArgs> IsDoneYetCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoyTestClient.ServiceReference1.Service1Soap.BeginInit(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInit(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int PoyTestClient.ServiceReference1.Service1Soap.EndInit(System.IAsyncResult result) {
            return base.Channel.EndInit(result);
        }
        
        private System.IAsyncResult OnBeginInit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PoyTestClient.ServiceReference1.Service1Soap)(this)).BeginInit(callback, asyncState);
        }
        
        private object[] OnEndInit(System.IAsyncResult result) {
            int retVal = ((PoyTestClient.ServiceReference1.Service1Soap)(this)).EndInit(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInitCompleted(object state) {
            if ((this.InitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InitCompleted(this, new InitCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InitAsync() {
            this.InitAsync(null);
        }
        
        public void InitAsync(object userState) {
            if ((this.onBeginInitDelegate == null)) {
                this.onBeginInitDelegate = new BeginOperationDelegate(this.OnBeginInit);
            }
            if ((this.onEndInitDelegate == null)) {
                this.onEndInitDelegate = new EndOperationDelegate(this.OnEndInit);
            }
            if ((this.onInitCompletedDelegate == null)) {
                this.onInitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInitCompleted);
            }
            base.InvokeAsync(this.onBeginInitDelegate, null, this.onEndInitDelegate, this.onInitCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoyTestClient.ServiceReference1.Service1Soap.BeginAddFile(PoyTestClient.ServiceReference1.AddFileRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddFile(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAddFile(int jobId, byte[] fileData, string fileName, System.AsyncCallback callback, object asyncState) {
            PoyTestClient.ServiceReference1.AddFileRequest inValue = new PoyTestClient.ServiceReference1.AddFileRequest();
            inValue.Body = new PoyTestClient.ServiceReference1.AddFileRequestBody();
            inValue.Body.jobId = jobId;
            inValue.Body.fileData = fileData;
            inValue.Body.fileName = fileName;
            return ((PoyTestClient.ServiceReference1.Service1Soap)(this)).BeginAddFile(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PoyTestClient.ServiceReference1.AddFileResponse PoyTestClient.ServiceReference1.Service1Soap.EndAddFile(System.IAsyncResult result) {
            return base.Channel.EndAddFile(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndAddFile(System.IAsyncResult result) {
            PoyTestClient.ServiceReference1.AddFileResponse retVal = ((PoyTestClient.ServiceReference1.Service1Soap)(this)).EndAddFile(result);
            return retVal.Body.AddFileResult;
        }
        
        private System.IAsyncResult OnBeginAddFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int jobId = ((int)(inValues[0]));
            byte[] fileData = ((byte[])(inValues[1]));
            string fileName = ((string)(inValues[2]));
            return this.BeginAddFile(jobId, fileData, fileName, callback, asyncState);
        }
        
        private object[] OnEndAddFile(System.IAsyncResult result) {
            bool retVal = this.EndAddFile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddFileCompleted(object state) {
            if ((this.AddFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddFileCompleted(this, new AddFileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddFileAsync(int jobId, byte[] fileData, string fileName) {
            this.AddFileAsync(jobId, fileData, fileName, null);
        }
        
        public void AddFileAsync(int jobId, byte[] fileData, string fileName, object userState) {
            if ((this.onBeginAddFileDelegate == null)) {
                this.onBeginAddFileDelegate = new BeginOperationDelegate(this.OnBeginAddFile);
            }
            if ((this.onEndAddFileDelegate == null)) {
                this.onEndAddFileDelegate = new EndOperationDelegate(this.OnEndAddFile);
            }
            if ((this.onAddFileCompletedDelegate == null)) {
                this.onAddFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddFileCompleted);
            }
            base.InvokeAsync(this.onBeginAddFileDelegate, new object[] {
                        jobId,
                        fileData,
                        fileName}, this.onEndAddFileDelegate, this.onAddFileCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoyTestClient.ServiceReference1.Service1Soap.BeginSubmit(PoyTestClient.ServiceReference1.SubmitRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSubmit(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSubmit(int jobId, System.AsyncCallback callback, object asyncState) {
            PoyTestClient.ServiceReference1.SubmitRequest inValue = new PoyTestClient.ServiceReference1.SubmitRequest();
            inValue.Body = new PoyTestClient.ServiceReference1.SubmitRequestBody();
            inValue.Body.jobId = jobId;
            return ((PoyTestClient.ServiceReference1.Service1Soap)(this)).BeginSubmit(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PoyTestClient.ServiceReference1.SubmitResponse PoyTestClient.ServiceReference1.Service1Soap.EndSubmit(System.IAsyncResult result) {
            return base.Channel.EndSubmit(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private byte[] EndSubmit(System.IAsyncResult result) {
            PoyTestClient.ServiceReference1.SubmitResponse retVal = ((PoyTestClient.ServiceReference1.Service1Soap)(this)).EndSubmit(result);
            return retVal.Body.SubmitResult;
        }
        
        private System.IAsyncResult OnBeginSubmit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int jobId = ((int)(inValues[0]));
            return this.BeginSubmit(jobId, callback, asyncState);
        }
        
        private object[] OnEndSubmit(System.IAsyncResult result) {
            byte[] retVal = this.EndSubmit(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubmitCompleted(object state) {
            if ((this.SubmitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitCompleted(this, new SubmitCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubmitAsync(int jobId) {
            this.SubmitAsync(jobId, null);
        }
        
        public void SubmitAsync(int jobId, object userState) {
            if ((this.onBeginSubmitDelegate == null)) {
                this.onBeginSubmitDelegate = new BeginOperationDelegate(this.OnBeginSubmit);
            }
            if ((this.onEndSubmitDelegate == null)) {
                this.onEndSubmitDelegate = new EndOperationDelegate(this.OnEndSubmit);
            }
            if ((this.onSubmitCompletedDelegate == null)) {
                this.onSubmitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitDelegate, new object[] {
                        jobId}, this.onEndSubmitDelegate, this.onSubmitCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PoyTestClient.ServiceReference1.Service1Soap.BeginIsDoneYet(int jobId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIsDoneYet(jobId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool PoyTestClient.ServiceReference1.Service1Soap.EndIsDoneYet(System.IAsyncResult result) {
            return base.Channel.EndIsDoneYet(result);
        }
        
        private System.IAsyncResult OnBeginIsDoneYet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int jobId = ((int)(inValues[0]));
            return ((PoyTestClient.ServiceReference1.Service1Soap)(this)).BeginIsDoneYet(jobId, callback, asyncState);
        }
        
        private object[] OnEndIsDoneYet(System.IAsyncResult result) {
            bool retVal = ((PoyTestClient.ServiceReference1.Service1Soap)(this)).EndIsDoneYet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnIsDoneYetCompleted(object state) {
            if ((this.IsDoneYetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IsDoneYetCompleted(this, new IsDoneYetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IsDoneYetAsync(int jobId) {
            this.IsDoneYetAsync(jobId, null);
        }
        
        public void IsDoneYetAsync(int jobId, object userState) {
            if ((this.onBeginIsDoneYetDelegate == null)) {
                this.onBeginIsDoneYetDelegate = new BeginOperationDelegate(this.OnBeginIsDoneYet);
            }
            if ((this.onEndIsDoneYetDelegate == null)) {
                this.onEndIsDoneYetDelegate = new EndOperationDelegate(this.OnEndIsDoneYet);
            }
            if ((this.onIsDoneYetCompletedDelegate == null)) {
                this.onIsDoneYetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIsDoneYetCompleted);
            }
            base.InvokeAsync(this.onBeginIsDoneYetDelegate, new object[] {
                        jobId}, this.onEndIsDoneYetDelegate, this.onIsDoneYetCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PoyTestClient.ServiceReference1.Service1Soap CreateChannel() {
            return new Service1SoapClientChannel(this);
        }
        
        private class Service1SoapClientChannel : ChannelBase<PoyTestClient.ServiceReference1.Service1Soap>, PoyTestClient.ServiceReference1.Service1Soap {
            
            public Service1SoapClientChannel(System.ServiceModel.ClientBase<PoyTestClient.ServiceReference1.Service1Soap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginInit(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Init", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInit(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("Init", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddFile(PoyTestClient.ServiceReference1.AddFileRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AddFile", _args, callback, asyncState);
                return _result;
            }
            
            public PoyTestClient.ServiceReference1.AddFileResponse EndAddFile(System.IAsyncResult result) {
                object[] _args = new object[0];
                PoyTestClient.ServiceReference1.AddFileResponse _result = ((PoyTestClient.ServiceReference1.AddFileResponse)(base.EndInvoke("AddFile", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSubmit(PoyTestClient.ServiceReference1.SubmitRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Submit", _args, callback, asyncState);
                return _result;
            }
            
            public PoyTestClient.ServiceReference1.SubmitResponse EndSubmit(System.IAsyncResult result) {
                object[] _args = new object[0];
                PoyTestClient.ServiceReference1.SubmitResponse _result = ((PoyTestClient.ServiceReference1.SubmitResponse)(base.EndInvoke("Submit", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginIsDoneYet(int jobId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = jobId;
                System.IAsyncResult _result = base.BeginInvoke("IsDoneYet", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndIsDoneYet(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("IsDoneYet", _args, result)));
                return _result;
            }
        }
    }
}
