// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PoyService {
	
	
	public partial class Application {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox Name;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
		
		protected System.Web.UI.WebControls.TextBox Organzation;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox description;
		
		protected System.Web.UI.WebControls.Button SubmitApplication;
	}
}
